name: Publish to GitHub Container Registry
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -t ghcr.io/${{ github.repository }}/inventory:latest -f apps/inventory/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/inventory:latest
          docker build -t ghcr.io/${{ github.repository }}/order:latest -f apps/order/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/order:latest
